/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Input {
  /**
   * The API endpoint to call
   */
  endpoint: string;
  /**
   * The HTTP method to use ['GET', 'POST', 'PUT', 'DELETE']
   */
  method: string;
  /**
   * The data to send with the request
   */
  data?: string;
}
